-- Insert sample airdrops data
INSERT INTO airdrops (
    name, logo, description, action, category, status, reward, start_date, difficulty,
    social_links, about, steps, requirements, is_hot, is_confirmed, participants, rating, total_ratings
) VALUES 
(
    'Lendasat',
    '/placeholder.svg?height=48&width=48&text=L',
    'Decentralized lending protocol with innovative borrowing mechanisms',
    'Borrow or lend',
    'latest',
    'active',
    '$50-500 LEND',
    '2024-07-15',
    'Medium',
    '{"telegram": "https://t.me/lendasat", "twitter": "https://twitter.com/lendasat", "discord": "https://discord.gg/lendasat", "website": "https://lendasat.io"}',
    '{"overview": "Lendasat is a revolutionary decentralized lending protocol that introduces innovative borrowing mechanisms to the DeFi ecosystem.", "tokenomics": "Total Supply: 1B LEND tokens. 40% for community rewards, 25% for team (4-year vesting), 20% for ecosystem development, 15% for strategic partnerships", "roadmap": "Q2 2024: Mainnet launch, Q3 2024: Cross-chain integration, Q4 2024: Mobile app release"}',
    '["Connect your wallet to Lendasat platform at lendasat.io", "Complete KYC verification process (required for higher limits)", "Make a minimum deposit of $100 USDC or equivalent", "Perform at least 3 lending or borrowing transactions", "Hold your position for minimum 30 days to qualify", "Participate in community governance voting (optional bonus)"]',
    '["Minimum $100 deposit required", "Valid wallet connection (MetaMask, WalletConnect supported)", "Complete KYC verification for full benefits", "Active participation for 30+ days", "Join official Telegram group for updates"]',
    false,
    false,
    1234,
    4.2,
    156
),
(
    'Scroll Protocol',
    '/placeholder.svg?height=48&width=48&text=S',
    'Layer 2 scaling solution with zkEVM technology',
    'Bridge and interact',
    'latest',
    'active',
    'TBA SCR',
    '2024-08-20',
    'Easy',
    '{"telegram": "https://t.me/scrollprotocol", "twitter": "https://twitter.com/scroll_zkp", "website": "https://scroll.io"}',
    '{"overview": "Scroll is a Layer 2 scaling solution built with zkEVM technology for Ethereum scalability.", "tokenomics": "SCR token distribution TBA", "roadmap": "Q3 2024: Token launch, Q4 2024: Mainnet optimization"}',
    '["Bridge ETH to Scroll network", "Interact with native dApps", "Provide liquidity on DEXs", "Complete weekly tasks", "Hold bridged assets for 30+ days"]',
    '["Minimum $50 bridge", "Complete 5+ transactions", "Use 3+ dApps", "Active for 30+ days"]',
    false,
    false,
    2567,
    4.6,
    234
),
(
    'MEXC',
    '/placeholder.svg?height=48&width=48&text=M',
    'Leading cryptocurrency exchange with global reach',
    'Register and Deposit, Trade',
    'hottest',
    'confirmed',
    '$25-1000 MX',
    '2024-06-30',
    'Easy',
    '{"telegram": "https://t.me/mexcofficial", "twitter": "https://twitter.com/mexc_official", "website": "https://mexc.com"}',
    '{"overview": "MEXC is a leading cryptocurrency exchange providing secure and efficient trading services globally.", "tokenomics": "MX token serves as the native utility token for the MEXC ecosystem", "roadmap": "Continuous platform development and feature expansion"}',
    '["Register new MEXC account", "Complete identity verification", "Make first deposit of $50+", "Complete 5 trades worth $100+ each", "Refer 2 friends to join"]',
    '["New users only", "Minimum $50 deposit", "Complete KYC Level 2", "Trade volume $500+"]',
    true,
    true,
    5432,
    4.7,
    892
),
(
    'Warden Protocol',
    '/placeholder.svg?height=48&width=48&text=W',
    'AI-powered crypto co-pilot for seamless DeFi interactions',
    'Start earning PUMPS',
    'hottest',
    'active',
    '1000-5000 PUMPS',
    '2024-08-01',
    'Easy',
    '{"telegram": "https://t.me/wardenprotocol", "twitter": "https://twitter.com/wardenprotocol", "website": "https://warden.xyz"}',
    '{"overview": "Warden Protocol is an AI-powered crypto co-pilot that simplifies DeFi interactions through intelligent automation.", "tokenomics": "PUMPS token rewards for early adopters and active users", "roadmap": "Q3 2024: AI features expansion, Q4 2024: Mobile app launch"}',
    '["Connect wallet to Warden Protocol", "Complete onboarding tutorial", "Perform 10 AI-assisted transactions", "Stake minimum 100 WARDEN tokens", "Use voice commands 5 times"]',
    '["Compatible wallet", "Minimum 100 WARDEN tokens", "Complete tutorial", "Active usage for 14 days"]',
    true,
    false,
    3240,
    4.5,
    324
),
(
    'LayerZero',
    '/placeholder.svg?height=48&width=48&text=LZ',
    'Omnichain interoperability protocol connecting all blockchains',
    'Bridge assets across chains',
    'potential',
    'upcoming',
    'TBA ZRO',
    '2024-09-15',
    'Hard',
    '{"telegram": "https://t.me/layerzeroprotocol", "twitter": "https://twitter.com/layerzero_labs", "website": "https://layerzero.network"}',
    '{"overview": "LayerZero is an omnichain interoperability protocol designed to connect all blockchains seamlessly.", "tokenomics": "ZRO token distribution and utility TBA", "roadmap": "Q4 2024: Token launch, 2025: Full omnichain deployment"}',
    '["Bridge assets between different chains", "Use LayerZero-powered dApps", "Provide liquidity on supported DEXs", "Complete cross-chain transactions", "Hold bridged assets for 60+ days"]',
    '["Multi-chain wallet setup", "Minimum $500 bridge volume", "Use 3+ different chains", "Active for 60+ days"]',
    false,
    false,
    8901,
    4.8,
    1247
);
